server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "${peervault.frontend-origin}"
            allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/api/v1/devices/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/files/**,/api/v1/sandbox/**
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/api/v1/transfers/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/audit/**,/api/v1/threats/**,/api/v1/security/**
        - id: share-service
          uri: lb://share-service
          predicates:
            - Path=/api/v1/share/**
        - id: notification-service-ws
          uri: lb:ws://notification-service
          predicates:
            - Path=/ws/**
